---
env:
  contexts:
  -name: "Default Context"
    urls:
    -"https://resellerportal.develop.redeam.io"
    includePaths:
    -"https://resellerportal.develop.redeam.io.*"
    excludePaths: []
    authentication:
      method: "json"
      parameters:
        loginPageUrl: "https://resellerportal.develop.redeam.io/api/login"
        loginRequestUrl: "https://resellerportal.develop.redeam.io/api/login"
        loginRequestBody: "{\"email\":\"{%username%}\",\"password\":\"{%password%}\"\
          }"
      verification:
        method: "response"
        loggedOutRegex: "\\QReseller Portal\\E"
        pollFrequency: 60
        pollUnits: "requests"
        pollUrl: ""
        pollPostData: ""
    sessionManagement:
      method: "cookie"
      parameters: {}
    users:
    -name: "admin"
      credentials:
        password: "cybage@123"
        username: "pentestla@mail.com"
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
-parameters:
    scanOnlyInScope: true
    enableTags: false
  rules: []
  name: "passiveScan-config"
  type: "passiveScan-config"
-parameters: {}
  name: "spider"
  type: "spider"
  tests:
  -onFail: "INFO"
    statistic: "automation.spider.urls.added"
    site: ""
    operator: ">="
    value: 100
    name: "At least 100 URLs found"
    type: "stats"
-parameters:
    maxDuration: 60
    maxCrawlDepth: 10
    numberOfBrowsers: 1
  name: "spiderAjax"
  type: "spiderAjax"
  tests:
  -onFail: "INFO"
    statistic: "spiderAjax.urls.added"
    site: ""
    operator: ">="
    value: 100
    name: "At least 100 URLs found"
    type: "stats"
-parameters: {}
  name: "passiveScan-wait"
  type: "passiveScan-wait"
-parameters:
    template: "risk-confidence-html"
    reportDir: "C:\\Users\\admin"
    reportTitle: "ZAP Scanning Report"
    reportDescription: ""
  name: "report"
  type: "report"

