  version: 2.1
  jobs:
    test-python-app:
      working_directory: ~/CircleCI-MultipleOrbs/flask-api
      docker:
        - image: cimg/python:3.9.2
      steps:
        - checkout:
            path: ~/CircleCI-MultipleOrbs
        - run:
            name: Install pip packages
            command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install -r requirements.txt

        - run:
            name: Test with pytest
            command: |
              . venv/bin/activate
              pytest
            
    test-node-app:
      working_directory: ~/CircleCI-MultipleOrbs/nodejs-cli
      docker:
        - image: cimg/node:10.16.3
      steps:
        - checkout:
            path: ~/CircleCI-MultipleOrbs
        - run:
            name: update npm
            command: "npm install -g npm@5"
        - restore_cache:
            key: dependency-cache-{{ checksum "package-lock.json" }}
        - run:
            name: install dependencies
            command: npm install
        - save_cache:
            key: dependency-cache-{{ checksum "package-lock.json" }}
            paths:
              - ./node_modules
        - run:
            name: run tests
            command: npm test
        - store_artifacts:
            path: ~/palatial-cakes-cli/__tests__

    test-scan:
      docker:
        - image: cimg/base:current
      steps:
        - checkout
        
        - setup_remote_docker:
            version: 20.10.23
            docker_layer_caching: true
            
        - run:
              command: |
                pwd
                ls
                docker run -u root -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py -t "https://resellerportal.develop.redeam.io" -I -r report.html              
                ls
        - store_artifacts:
            path: /zap/wrk
            destination: zap-report

  workflows:
    test:
      jobs:
        - test-scan
